.github/workflows/ci.yaml:
  env:
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 4.4.0.Final
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 6.0.1
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 7.0.0
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 7.0.1
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 8.0.0
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 8.0.1
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 9.0.0
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 9.0.2
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: 9.0.3
      DIR: .
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/keycloak
      TAG: latest
      DIR: .
      SQUASH: 'true'
  buildArgs:
    - TAG
